Core21Identity/Controllers/AAppsPubsPatsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Core21Identity.Controllers
{
    [Authorize(Roles = "Free,Premium")]
    public class AAppsPubsPatsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Core21Identity/Controllers/ExaminersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Core21Identity.Controllers
{
    [Authorize(Roles = "Premium")]
    public class ExaminersController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Core21Identity/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Core21Identity.Data;
using Core21Identity.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Stripe;

namespace Core21Identity.Controllers
{
    public class ProfileController : Controller
    {
        private UserManager<ApplicationUser> _userManager;
        private ApplicationIdentityDbContext _dbContext;

        public ProfileController(UserManager<ApplicationUser> userManager, ApplicationIdentityDbContext dbContext)
        {
            _userManager = userManager;
            _dbContext = dbContext;
        }
        public async Task<IActionResult> Index()
        {
            ProfileViewModel model = new ProfileViewModel();

            ApplicationUser user = await _userManager.GetUserAsync(User);
            var roles = (await _userManager.GetRolesAsync(user)).ToArray();


            model.UserName = user.UserName;
            model.Email = user.Email;
            model.UserPlanStartDate = user.UserPlanStartDate;
            model.UserPlanExpireDate = user.UserPlanExpireDate;
            model.Roles = string.Join(",", roles);
            model.UserTypeId = user.UserTypeId;


            List<UserPlanType> userPlanTypes = _dbContext.UserPlanTypes.ToList();
            model.UserPlanTypes = userPlanTypes;

            return View(model);
        }

    }
}

Core21Identity/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Core21Identity</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Core21Identity</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    @if ((await AuthorizationService.AuthorizeAsync(User, "FreePolicy")).Succeeded)
                    {
                        <li><a style="color:lightgreen" asp-area="" asp-controller="AAppsPubsPats" asp-action="Index">AApps/Pubs/Pats</a></li>
                        <li><a style="color:gold;" asp-controller="Profile" asp-action="Index">Become a Premium Member!</a></li>
                    }
                    }
                    @if ((await AuthorizationService.AuthorizeAsync(User, "PremiumPolicy")).Succeeded)
                    {
                        <li><a style="color:lightgreen" asp-area="" asp-controller="AAppsPubsPats" asp-action="Index">AApps/Pubs/Pats</a></li>
                        <li><a style="color:gold" asp-area="" asp-controller="Examiners" asp-action="Index">Examiners</a></li>
                    }
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Core21Identity</p>
        </footer>
    </div>



    @RenderSection("Scripts", required: false)
</body>
</html>